### PR TITLE
Simplified code.

### PR DESCRIPTION
**Pull request by pbzdyl**
Wouldn't it be more idiomatic to use list* instead of combination of concat and list?

### CODE REVIEW

**Comment by trptcolin** [comment]
How would you feel about `cons` instead? The nice thing about `cons` is that it's already been covered in a previous koan (`concat` hasn't been explicitly introduced, same for `list*`).

**Comment by pbzdyl** [comment]
Yes, you are right, it would be even simpler. Let me change it.

**Comment by trptcolin** [comment]
Nice, thanks! Would you mind [squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) these 2 commits?

**Comment by pbzdyl** [comment]
Done.

**Comment by trptcolin** [comment]
Woohoo thanks!!  :heart:

**Pull request merged**
